name: Build and Push Nginx to NHN Cloud NCR

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # GitHub repository checkout
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up Docker
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Login to NHN Cloud NCR
    - name: Login to NHN Cloud NCR
      run: |
        echo "${{ secrets.NHN_NCR_PASSWORD }}" | docker login -u "${{ secrets.NHN_NCR_USERNAME }}" --password-stdin 4e06a9e9-kr1-registry.container.nhncloud.com/ncr-for-web

    # Build Nginx Docker image
    - name: Build Nginx Docker Image
      run: |
        docker build -t 4e06a9e9-kr1-registry.container.nhncloud.com/ncr-for-web/nginx:latest .

    # Push Docker image to NHN Cloud NCR
    - name: Push to NHN Cloud NCR
      run: |
        docker push 4e06a9e9-kr1-registry.container.nhncloud.com/ncr-for-web/nginx:latest
