name: Build, Push Nginx to NHN Cloud NCR, and Deploy with ArgoCD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # GitHub repository checkout
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up Docker
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Login to NHN Cloud NCR
    - name: Login to NHN Cloud NCR
      run: |
        echo "${{ secrets.NHN_NCR_PASSWORD }}" | docker login -u "${{ secrets.NHN_NCR_USERNAME }}" --password-stdin 4e06a9e9-kr1-registry.container.nhncloud.com/ncr-for-web

    # Build Nginx Docker image
    - name: Build Nginx Docker Image
      run: |
        docker build -t 4e06a9e9-kr1-registry.container.nhncloud.com/ncr-for-web/nginx:latest .

    # Push Docker image to NHN Cloud NCR
    - name: Push to NHN Cloud NCR
      run: |
        docker push 4e06a9e9-kr1-registry.container.nhncloud.com/ncr-for-web/nginx:latest

    # Set up Kustomize
    - name: Set up Kustomize
      uses: kubernetes-sigs/setup-kustomize@v2
      with:
        version: 'latest'

    # Generate Kustomize manifests
    - name: Generate Kustomize manifests
      run: |
        kustomize build k8s-manifests/base > k8s-manifests/base/generated.yaml

    # Set up ArgoCD CLI
    - name: Set up ArgoCD CLI
      uses: argoproj/argo-cd-action@v1
      with:
        version: 'latest'

    # Login to ArgoCD
    - name: ArgoCD Login
      run: |
        argocd login <ARGOCD_SERVER> --username ${{ secrets.ARGOCD_USERNAME }} --password ${{ secrets.ARGOCD_PASSWORD }}

    # Sync application with ArgoCD
    - name: Sync Application with ArgoCD
      run: |
        argocd app sync cicd-pipeline --retry
