name: Build, Push, and Deploy Nginx using ArgoCD
on:
  push:
    branches:
      - main
env:
  DOCKER_REGISTRY: 4e06a9e9-kr1-registry.container.nhncloud.com
  DOCKER_REPOSITORY: ncr-for-web
  IMAGE_NAME: nginx
  ARGOCD_APP_NAME: cicd-pipeline

jobs:
  build-push-update:
    runs-on: ubuntu-latest

    steps:
    # GitHub repository checkout
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up Docker Buildx
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Login to NHN Cloud NCR
    - name: Login to NHN Cloud NCR
      run: |
        echo "${{ secrets.NHN_NCR_PASSWORD }}" | docker login -u "${{ secrets.NHN_NCR_USERNAME }}" --password-stdin ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_REPOSITORY }}

    # Build and push Nginx Docker image
    - name: Build and Push Nginx Docker Image
      run: |
        TAG_NAME=$(date +'%Y%m%d%H%M%S')
        IMAGE_URI=${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_REPOSITORY }}/${{ env.IMAGE_NAME }}:$TAG_NAME
        docker build -t $IMAGE_URI .
        docker push $IMAGE_URI
        echo "IMAGE_URI=$IMAGE_URI" >> $GITHUB_ENV
      working-directory: ./web

    # Setup Kustomize
    - name: Setup Kustomize
      uses: imranismail/setup-kustomize@v1

    # Checkout k8s-manifests repository
    - name: Checkout k8s-manifests repository
      uses: actions/checkout@v3
      with:
        repository: netsoul-test/k8s-manifests
        ref: main
        token: ${{ secrets.ACTION_TOKEN }}
        path: k8s-manifests

    # Setup Git identity
    - name: Setup Git identity
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
      working-directory: ./k8s-manifests

    # Update Kubernetes manifest with new image URI
    - name: Update web-deployment.yaml with new image URI and tag
      run: |
        sed -i "s|image: .*|image: $IMAGE_URI|" ./k8s-manifests/base/web-deployment.yaml
        cat ./k8s-manifests/base/web-deployment.yaml # For debugging purposes
      working-directory: ./k8s-manifests
      env:
        IMAGE_URI: ${{ env.IMAGE_URI }}

    # Commit and push the updated web-deployment.yaml
    - name: Commit and push the updated web-deployment.yaml
      run: |
        git add base/web-deployment.yaml
        git commit -m "Update image URI for Nginx to $IMAGE_URI"
        git push
      working-directory: ./k8s-manifests
      env:
        IMAGE_URI: ${{ env.IMAGE_URI }}

    # Trigger ArgoCD sync
    - name: Trigger ArgoCD sync
      run: |
        curl -sSL -o argocd-linux-amd64 https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
        chmod +x argocd-linux-amd64
        ./argocd-linux-amd64 login ${{ secrets.ARGOCD_SERVER }} --username ${{ secrets.ARGOCD_USERNAME }} --password ${{ secrets.ARGOCD_PASSWORD }} --insecure
        ./argocd-linux-amd64 app sync ${{ env.ARGOCD_APP_NAME }} --prune
        rm argocd-linux-amd64
